### ISSUE TITLE
superagent-wrapper's decodeExpecting does not decode error responses

### ISSUE THREAD

**Issue by jonball4** [BitGo/api-ts#137] opened 2022-06-29 12:44 UTC
The experience using superagent-wrapper in production code would be much improved if `decodeExpecting` would also decode the response if the expected status code was not returned by the request.  

In the current beta version, a barebones error message is returned complaining about an incorrect status code:

https://github.com/BitGo/api-ts/blob/8a460d6d629eb7cdc84afb2b195347242e9cf8d4/packages/superagent-wrapper/src/request.ts#L153-L167

The error message would be more helpful if it included a stringified version of the decoded error response, if a codec is defined for the unexpected status code returned.

Some food for thought - In order to work around this limitation of `decodeExpecting`, I had written a helper method in one of my use cases to create a more useful error message taking the error response into account:

```typescript
const unknownResponseToError = (operation: string) => (response: { body: unknown }) => pipe(
  response.body,
  Json.stringify,
  E.match(
    () => new BNError('DAS API Request returned an unreadable response', DAS_API_ERROR, response),
    (stringifiedBody: string) => new BNError(
      `DAS API Request for '${operation}' returned an unexpected response: ${stringifiedBody}`,
      DAS_API_ERROR
    ),
  )
);

const processDecodedResponse = <R extends HttpRoute>(
  httpRoute: R, operation: string,
) => TE.chainEitherK(
    (decodedResponse: {
      body: unknown
  }): E.Either<Error, t.TypeOf<R['response'][200]>> => pipe(
      decodedResponse.body,
      E.fromPredicate(
        httpRoute.response[200].is,
        () => unknownResponseToError(operation)(decodedResponse)
      )
    )
  );

```

**Comment by bitgopatmcl** [comment] 2022-06-29 15:53
It should be possible to do this, although `decodeExpecting` throws when it gets the unknown status code, so the catching code would need to handle the wider error type.

Does the regular `decode` work for your use-case? It isn't supposed to throw (it used to because of unexpected behavior in superagent, but that has been fixed), and it gives you a tagged union of all the possible responses along with a catch-all one for decoding errors.

**Comment by jonball4** [comment] 2022-07-07 18:13
> > If `decodeExpecting` threw an error including the body of the response, then I would be able wrap it in a `TE.tryCatch` and just pass along the error via `identity`
> 
> Do you have an assumption that the `thrown` value will always be an `Error`? I'm trying to make sense of this last sentence in the context of the preceding text

Yes

**Comment by bitgopatmcl** [comment] 2022-07-08 15:27
I guess at the very least we could subclass `Error` with the appropriate fields and export it so it can be quickly narrowed by an `instanceof` check.

**Comment by ericcrosson-bitgo** [comment] 2022-07-19 23:47
Closed by https://github.com/BitGo/api-ts/pull/162

**Closed by ericcrosson-bitgo** 2022-07-19 23:47 UTC
